spring.application.name=Rizz
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/aileks
spring.datasource.username=aileks
spring.jpa.properties.hibernate.default_schema=rizztasks
spring.jpa.hibernate.ddl-auto=update
